Pages/AddCustomer.cshtml.cs
using BAIS3150Project.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BAIS3150Project.Pages
{
    public class AddCustomerModel : PageModel
    {
        public string Message { get; set; }
        [BindProperty]
        public string CustomerId { get; set; }
        [BindProperty]
        public string CustomerName { get; set; }
        [BindProperty]
        public string Address { get; set; }
        [BindProperty]
        public string City { get; set; }
        [BindProperty]
        public string Province { get; set; }
        [BindProperty]
        public string PostalCode { get; set; }
        
        public void OnGet()
        {
        }
        
        public void OnPost()
        {
            if (CustomerId == null)
            {
                ModelState.AddModelError("CustomerId", "Customer Id is required");
            }
            else if (CustomerName == null)
            {
                ModelState.AddModelError("CustomerName", "Customer Name is required");
            }
            else if (Address == null)
            {
                ModelState.AddModelError("Address", "Address is required");
            }
            else if (City == null)
            {
                ModelState.AddModelError("City", "City is required");
            }
            else if (Province == null)
            {
                ModelState.AddModelError("Province", "Province is required");
            }
            else if (PostalCode == null)
            {
                ModelState.AddModelError("PostalCode", "Postal Code is required");
            }

            if (ModelState.IsValid)
            {
                bool Confirmation;
                Customer ACustomer = new()
                {
                    CustomerId = CustomerId,
                    CustomerName = CustomerName,
                    Address = Address,
                    City = City,
                    Province = Province,
                    PostalCode = PostalCode
                };
                ABCPOS ABCHardware = new();
                Confirmation = ABCHardware.AddCustomer(ACustomer);

                if (Confirmation)
                {
                    Message = "Customer was added successfully";
                }
                else
                {
                    Message = "Customer was added unsuccessfully";
                }
            }
            else
            {
                Message = "*** Invalid Inputs ***";
            }
        }
    }
}

Pages/AddItem.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BAIS3150Project.Domain;

namespace BAIS3150Project.Pages
{
    public class AddItemModel : PageModel
    {
        public string Message { get; set; }
        [BindProperty]
        public string ItemCode { get; set; }
        [BindProperty]
        public string Description { get; set; }
        [BindProperty]
        public decimal UnitPrice { get; set; }
        [BindProperty]
        public int Quantity { get; set; }
        public void OnGet()
        {
        }
        public void OnPost()
        {
            if (ItemCode == null)
            {
                ModelState.AddModelError("ItemCode", "Item Code is required");
            }
            else if (Description == null)
            {
                ModelState.AddModelError("Description", "Description is required");
            }
            else if (UnitPrice == 0)
            {
                ModelState.AddModelError("UnitPrice", "Unit Price is required");
            }
            else if (Quantity == 0)
            {
                ModelState.AddModelError("Quantity", "Quantity is required");
            }

            if (ModelState.IsValid)
            {
                bool Confirmation;
                Item AItem = new()
                {
                    ItemCode = ItemCode,
                    Description = Description,
                    UnitPrice = UnitPrice,
                    Quantity = Quantity
                };
                ABCPOS ABCHardware = new();
                Confirmation = ABCHardware.AddItem(AItem);

                if (Confirmation)
                {
                    Message = "Item was added successfully";
                }
                else
                {
                    Message = "Item was added unsuccessfully";
                }
            }
            else
            {
                Message = "*** Invalid Inputs ***";
            }
        }
    }
}

Pages/Customers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BAIS3150Project.Domain;

namespace BAIS3150Project.Pages
{
    public class CustomersModel : PageModel
    {
        public List<Customer> Customers { get; set; }
        public void OnGet()
        {
            ABCPOS ABCHardware = new();
            Customers = ABCHardware.GetAllCustomers();
        }

        public IActionResult OnPost(string action)
        {
            return action == "Add" ? RedirectToPage("AddCustomer") :
                    action == "Update" ? RedirectToPage("UpdateCustomer")
                    : RedirectToPage("DeleteCustomer");
        }
    }
}

Pages/DeleteCustomer.cshtml.cs
using BAIS3150Project.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BAIS3150Project.Pages
{
    public class DeleteCustomerModel : PageModel
    {
        public string Message { get; set; }
        [BindProperty]
        public string SearchCustomerId { get; set; }
        [BindProperty]
        public string CustomerId { get; set; }
        [BindProperty]
        public string CustomerName { get; set; }
        [BindProperty]
        public string Address { get; set; }
        [BindProperty]
        public string City { get; set; }
        [BindProperty]
        public string Province { get; set; }
        [BindProperty]
        public string PostalCode { get; set; }
        public void OnGet()
        {
        }

        public void OnPostSearch()
        {
            CustomerId = null;
            CustomerName = null;
            Address = null;
            City = null;
            Province = null;
            PostalCode = null;

            if (SearchCustomerId == null)
            {
                ModelState.AddModelError("SearchCustomerId", "Please Enter Customer Id");
            }

            if (ModelState.IsValid)
            {
                ABCPOS ABCHardware = new();
                Customer FoundCustomer = ABCHardware.GetCustomerById(SearchCustomerId);

                if (FoundCustomer.CustomerId == null)
                {
                    ModelState.AddModelError("SearchCustomerId", "Not Found");
                }
                else
                {
                    CustomerId = FoundCustomer.CustomerId;
                    CustomerName = FoundCustomer.CustomerName;
                    Address = FoundCustomer.Address;
                    City = FoundCustomer.City;
                    Province = FoundCustomer.Province;
                    PostalCode = FoundCustomer.PostalCode;
                }
            }
        }

        public void OnPostDelete()
        {
            if (CustomerId == null)
            {
                ModelState.AddModelError("CustomerId", "Customer Id is required");
            }
            if (CustomerName == null)
            {
                ModelState.AddModelError("CustomerName", "Customer Name is required");
            }
            if (Address == null)
            {
                ModelState.AddModelError("Address", "Address is required");
            }
            if (City == null)
            {
                ModelState.AddModelError("City", "City is required");
            }
            if (Province == null)
            {
                ModelState.AddModelError("Province", "Province is required");
            }
            if (PostalCode == null)
            {
                ModelState.AddModelError("PostalCode", "Postal Code is required");
            }

            if (ModelState.IsValid)
            {
                bool Confirmation;
                ABCPOS ABCHardware = new();
                Confirmation = ABCHardware.DeleteCustomer(CustomerId);

                if (Confirmation)
                {
                    Message = "Customer was deleted successfully";
                    CustomerId = null;
                    CustomerName = null;
                    Address = null;
                    City = null;
                    Province = null;
                    PostalCode = null;
                }
                else
                {
                    Message = "Customer was not deleted successfully";
                }
            }
            else
            {
                Message = "*** Invalid Inputs ***";
            }
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BAIS3150Project.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Items.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BAIS3150Project.Domain;

namespace BAIS3150Project.Pages
{
    public class ItemsModel : PageModel
    {
        public List<Item> Items { get; set; }
        public void OnGet()
        {
            ABCPOS ABCHardware = new();
            Items = ABCHardware.GetAllItems();
        }

        public IActionResult OnPost(string action)
        {
            return action == "Add" ? RedirectToPage("AddItem") :
                    action == "Update" ? RedirectToPage("UpdateItem")
                    : RedirectToPage("DeleteItem");
        }
    }
}

Pages/ProcessSale.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BAIS3150Project.Domain;
using System.Text.Json;

namespace BAIS3150Project.Pages
{
    public class ProcessSaleModel : PageModel
    {
        public string Message { get; set; }
        public List<Item> Items { get; set; }
        [BindProperty]
        public string CustomerId { get; set; }
        [BindProperty]
        public string SaleDate { get; set; }
        [BindProperty]
        public string SalePerson { get; set; }
        [BindProperty]
        public string SaleItems { get; set; }

        public Customer ACustomer { get; set; }
        public void OnGet()
        {
            ABCPOS ABCHardware = new();
            Items = ABCHardware.GetAllItems();

            ACustomer = new();
        }

        public void OnPostProcessSale()
        {
            ABCPOS ABCHardware = new();
            Items = ABCHardware.GetAllItems();

            
            // Document code-maze.com/introduction-system-text-json-examples
            List<SaleItem> SaleItemObjects = JsonSerializer.Deserialize<List<SaleItem>>(SaleItems, new JsonSerializerOptions { NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowReadingFromString });

            // Check Valid Sale
            bool isValid = true;

            // Set New Sale
            decimal subTotal = 0;
            decimal gst = 0;
            decimal saleTotal = 0;
            foreach( SaleItem obj in SaleItemObjects )
            {
                subTotal += obj.ItemTotal;
                int inventory = Items.Find(item => item.ItemCode == obj.AItem.ItemCode).Quantity;
                if ( inventory < obj.Quantity) isValid = false;
            }
            gst = subTotal * (decimal)0.05;
            saleTotal = subTotal + gst;

            if ( isValid )
            {
                Sale ASale = new()
                {
                    SaleDate = SaleDate,
                    SalePerson = SalePerson,
                    Customer = ABCHardware.GetCustomerById(CustomerId),
                    SaleItems = SaleItemObjects,
                    SubTotal = subTotal,
                    GST = gst,
                    Total = saleTotal
                };
                ABCHardware = new();
                int NewSaleNumber = ABCHardware.ProcessSale(ASale);

                // Reset
                ACustomer = new();
                CustomerId = "";
                SaleDate = "";
                SalePerson = "";
                SaleItems = "";

                // Testing
                // Message = ASale.SubTotal + "," + ASale.Total + "," + ASale.Customer.CustomerName + "," + ASale.SaleItems.ElementAt(0).AItem.ItemCode;
                Message = "Sale processed successfully - Sale Number: " + NewSaleNumber;
            }
            else
            {
                ACustomer = ABCHardware.GetCustomerById(CustomerId);
                Message = "Not enough items in inventory";
            }
        }

        public void OnPostSearchCustomer()
        {
            ABCPOS ABCHardware = new();
            Items = ABCHardware.GetAllItems();

            ACustomer = ABCHardware.GetCustomerById(CustomerId);


        }
    }
}

Pages/UpdateCustomer.cshtml.cs
using BAIS3150Project.Domain;
using BAIS3150Project.TechnicalService;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;

namespace BAIS3150Project.Pages
{
    public class UpdateCustomerModel : PageModel
    {
        public string Message { get; set; }
        [BindProperty]
        public string SearchCustomerId { get; set; }
        [BindProperty]
        public string CustomerId { get; set; }
        [BindProperty]
        public string CustomerName { get; set; }
        [BindProperty]
        public string Address { get; set; }
        [BindProperty]
        public string City { get; set; }
        [BindProperty]
        public string Province { get; set; }
        [BindProperty]
        public string PostalCode { get; set; }
        public void OnGet()
        {
        }

        public void OnPostSearch()
        {
            CustomerId = null;
            CustomerName = null;
            Address = null;
            City = null;
            Province = null;
            PostalCode = null;

            if (SearchCustomerId == null)
            {
                ModelState.AddModelError("SearchCustomerId", "Please Enter Customer Id");
            }

            if (ModelState.IsValid)
            {
                ABCPOS ABCHardware = new();
                Customer FoundCustomer = ABCHardware.GetCustomerById(SearchCustomerId);

                if (FoundCustomer.CustomerId == null)
                {
                    ModelState.AddModelError("SearchCustomerId", "Not Found");
                }
                else
                {
                    CustomerId = FoundCustomer.CustomerId;
                    CustomerName = FoundCustomer.CustomerName;
                    Address = FoundCustomer.Address;
                    City = FoundCustomer.City;
                    Province = FoundCustomer.Province;
                    PostalCode = FoundCustomer.PostalCode;
                }
            }
        }

        public void OnPostUpdate()
        {
            if (CustomerId == null)
            {
                ModelState.AddModelError("CustomerId", "Customer Id is required");
            }
            if (CustomerName == null)
            {
                ModelState.AddModelError("CustomerName", "Customer Name is required");
            }
            if (Address == null)
            {
                ModelState.AddModelError("Address", "Address is required");
            }
            if (City == null)
            {
                ModelState.AddModelError("City", "City is required");
            }
            if (Province == null)
            {
                ModelState.AddModelError("Province", "Province is required");
            }
            if (PostalCode == null)
            {
                ModelState.AddModelError("PostalCode", "Postal Code is required");
            }

            if (ModelState.IsValid)
            {
                bool Confirmation;
                Customer ACustomer = new()
                {
                    CustomerId = CustomerId,
                    CustomerName = CustomerName,
                    Address = Address,
                    City = City,
                    Province = Province,
                    PostalCode = PostalCode
                };
                ABCPOS ABCHardware = new();
                Confirmation = ABCHardware.UpdateCustomer(ACustomer);

                if (Confirmation)
                {
                    Message = "Customer was updated successfully";
                    CustomerId = null;
                    CustomerName = null;
                    Address = null;
                    City = null;
                    Province = null;
                    PostalCode = null;
                }
                else
                {
                    Message = "Customer was not updated successfully";
                }
            }
            else
            {
                Message = "*** Invalid Inputs ***";
            }
        }
    }
}

Pages/AddCustomer.cshtml
@page
@model BAIS3150Project.Pages.AddCustomerModel
@{
    Layout = "_Layout";
    ViewData["Tittle"] = "Add Customer";
}
@section scriptContent
    {
    <script type="text/javascript">
        function IsFormValid(aForm) {
            var isValid = false;

            // Get all fields
            var CustomerId = aForm.CustomerId.value;
            var CustomerName = aForm.CustomerName.value;
            var Address = aForm.Address.value;
            var City = aForm.City.value;
            var Province = aForm.Province.value;
            var PostalCode = aForm.PostalCode.value;

            if (CustomerId.length === 0) {
                alert("Customer Id is required");
            }
            else if (CustomerName.length === 0) {
                alert("Customer Name is required");
            }
            else if (Address.length === 0) {
                alert("Address is required");
            }
            else if (City.length === 0) {
                alert("City is required");
            }
            else if (Province.length === 0) {
                alert("Province is required");
            }
            else if (PostalCode.length === 0) {
                alert("Postal Code is required");
            }
            else {
                isValid = true;
            }

            return isValid;
        }
    </script>
}
<h1>Add Customer</h1>
<form name="form" method="post" onsubmit="return IsFormValid(window.document.form);">
    <table>
        <tr>
            <td>Customer Id:</td>
            <td>
                <input type="text" name="CustomerId" />
                @Html.ValidationMessage("CustomerId")
            </td>
        </tr>
        <tr>
            <td>Customer Name:</td>
            <td>
                <input type="text" name="CustomerName" />
                @Html.ValidationMessage("CustomerName")
            </td>
        </tr>
        <tr>
            <td>Address:</td>
            <td>
                <input type="text" name="Address" />
                @Html.ValidationMessage("Address")
            </td>
        </tr>
        <tr>
            <td>City:</td>
            <td>
                <input type="text" name="City" />
                @Html.ValidationMessage("City")
            </td>
        </tr>
        <tr>
            <td>Province:</td>
            <td>
                <input type="text" name="Province" />
                @Html.ValidationMessage("Province")
            </td>
        </tr>
        <tr>
            <td>Postal Code:</td>
            <td>
                <input type="text" name="PostalCode" />
                @Html.ValidationMessage("PostalCode")
            </td>
        </tr>
        <tr>
            <td colspan="2" align="right"><input type="submit" value="Add New" /></td>
        </tr>
    </table>
</form>
@Model.Message

Pages/Customers.cshtml
@page
@model BAIS3150Project.Pages.CustomersModel
@{
    Layout = "_Layout";
    ViewData["Tittle"] = "Customers";
}
@section styleContent
{
    <style>
        .tableFixHead {
            overflow-y: auto;
            height: 350px;
            width: 100%;
        }

            .tableFixHead thead th {
                position: sticky;
                top: 0;
            }

            .tableFixHead table {
                width: 100%;
            }

        th {
            background: #eee;
        }

        .actions input {
            width: 100px;
            margin: 10px;
        }
    </style>
}
<h1>Customer Management</h1>
<form name="form" method="post">
    <div class="actions">
        <input type="submit" value="Add New" asp-route-action="Add" />
        <input type="submit" value="Update" asp-route-action="Update" />
        <input type="submit" value="Delete" asp-route-action="Delete" />
    </div>
</form>
<div class="tableFixHead">
    <table border="1" cellspacing="0" cellpadding="7">
        <thead>
            <tr>
                <th>Customer Id</th>
                <th>Customer Name</th>
                <th>Address</th>
                <th>City</th>
                <th>Province</th>
                <th>Postal Code</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var Customer in Model.Customers)
                {
                    <tr>
                        <td>@Customer.CustomerId</td>
                        <td>@Customer.CustomerName</td>
                        <td>@Customer.Address</td>
                        <td>@Customer.City</td>
                        <td>@Customer.Province</td>
                        <td>@Customer.PostalCode</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Pages/DeleteCustomer.cshtml
@page
@model BAIS3150Project.Pages.DeleteCustomerModel
@{
    Layout = "_Layout";
    ViewData["Tittle"] = "Delete Customer";
}
<h1>Delete Customer</h1>
<form name="form" method="post">
    <table>
        <tr>
            <td>Customer Id:</td>
            <td>
                <input type="text" name="SearchCustomerId" />
            </td>
            <td>
                @Html.ValidationMessage("SearchCustomerId")
            </td>
        </tr>
        <tr>
            <td colspan="2" align="right">
                <input type="submit" value="Search" asp-page-handler="Search" />
            </td>
        </tr>
        <tr>
            <td>Customer Id:</td>
            <td>
                <input type="text" hidden name="CustomerId" value="@Model.CustomerId" />
                <input type="text" disabled value="@Model.CustomerId" />
            </td>
            <td>
                @Html.ValidationMessage("CustomerId")
            </td>
        </tr>
        <tr>
            <td>Customer Name:</td>
            <td>
                <input type="text" hidden name="CustomerName" value="@Model.CustomerName" />
                <input type="text" disabled value="@Model.CustomerName" />
            </td>
            <td>
                @Html.ValidationMessage("CustomerName")
            </td>
        </tr>
        <tr>
            <td>Address:</td>
            <td>
                <input type="text" hidden name="Address" value="@Model.Address" />
                <input type="text" disabled value="@Model.Address" />
            </td>
            <td>
                @Html.ValidationMessage("Address")
            </td>
        </tr>
        <tr>
            <td>City:</td>
            <td>
                <input type="text" hidden name="City" value="@Model.City" />
                <input type="text" disabled value="@Model.City" />
            </td>
            <td>
                @Html.ValidationMessage("City")
            </td>
        </tr>
        <tr>
            <td>Province:</td>
            <td>
                <input type="text" hidden name="Province" value="@Model.Province" />
                <input type="text" disabled value="@Model.Province" />
            </td>
            <td>
                @Html.ValidationMessage("Province")
            </td>
        </tr>
        <tr>
            <td>Postal Code:</td>
            <td>
                <input type="text" hidden name="PostalCode" value="@Model.PostalCode" />
                <input type="text" disabled value="@Model.PostalCode" />
            </td>
            <td>
                @Html.ValidationMessage("PostalCode")
            </td>
        </tr>
        <tr>
            <td colspan="2" align="right">
                <input type="submit" value="Delete" asp-page-handler="Delete" />
            </td>
        </tr>
    </table>
</form>
@Model.Message

Pages/DeleteItem.cshtml
@page
@model BAIS3150Project.Pages.DeleteItemModel
@{
    Layout = "_Layout";
    ViewData["Tittle"] = "Delete Item";
}
<h1>Delete Item</h1>
<form name="form" method="post">
    <table>
        <tr>
            <td>Item Code:</td>
            <td>
                <input type="text" name="SearchItemCode" />
            </td>
            <td>
                @Html.ValidationMessage("SearchItemCode")
            </td>
        </tr>
        <tr>
            <td colspan="2" align="right">
                <input type="submit" value="Search" asp-page-handler="Search" />
            </td>
        </tr>
        <tr>
            <td>Item Code:</td>
            <td>
                <input type="text" hidden name="ItemCode" value="@Model.ItemCode" />
                <input type="text" disabled value="@Model.ItemCode" />
            </td>
            <td>
                @Html.ValidationMessage("ItemCode")
            </td>
        </tr>
        <tr>
            <td>Description:</td>
            <td>
                <input type="text" hidden name="Description" value="@Model.Description" />
                <input type="text" disabled value="@Model.Description" />
            </td>
            <td>
                @Html.ValidationMessage("Description")
            </td>
        </tr>
        <tr>
            <td>Unit Price:</td>
            <td>
                <input type="text" hidden name="UnitPrice" value="@Model.UnitPrice" />
                <input type="text" disabled value="@Model.UnitPrice" />
            </td>
            <td>
                @Html.ValidationMessage("UnitPrice")
            </td>
        </tr>
        <tr>
            <td>Quantity:</td>
            <td>
                <input type="text" hidden name="Quantity" value="@Model.Quantity" />
                <input type="text" disabled value="@Model.Quantity" />
            </td>
            <td>
                @Html.ValidationMessage("Quantity")
            </td>
        </tr>
        <tr>
            <td colspan="2" align="right">
                <input type="submit" value="Delete" asp-page-handler="Delete" />
            </td>
        </tr>
    </table>
</form>
@Model.Message

Pages/UpdateCustomer.cshtml
@page
@model BAIS3150Project.Pages.UpdateCustomerModel
@{
    Layout = "_Layout";
    ViewData["Tittle"] = "Update Customer";
}
<h1>Update Customer</h1>
<form name="form" method="post">
    <table>
        <tr>
            <td>Customer Id:</td>
            <td>
                <input type="text" name="SearchCustomerId" />
            </td>
            <td>
                @Html.ValidationMessage("SearchCustomerId")
            </td>
        </tr>
        <tr>
            <td colspan="2" align="right">
                <input type="submit" value="Search" asp-page-handler="Search" />
            </td>
        </tr>
        <tr>
            <td>Customer Id:</td>
            <td>
                <input type="text" hidden name="CustomerId" value="@Model.CustomerId" />
                <input type="text" disabled value="@Model.CustomerId" />
            </td>
            <td>
                @Html.ValidationMessage("CustomerId")
            </td>
        </tr>
        <tr>
            <td>Customer Name:</td>
            <td>
                <input type="text" name="CustomerName" value="@Model.CustomerName" />
            </td>
            <td>
                @Html.ValidationMessage("CustomerName")
            </td>
        </tr>
        <tr>
            <td>Address:</td>
            <td>
                <input type="text" name="Address" value="@Model.Address" />
            </td>
            <td>
                @Html.ValidationMessage("Address")
            </td>
        </tr>
        <tr>
            <td>City:</td>
            <td>
                <input type="text" name="City" value="@Model.City" />
            </td>
            <td>
                @Html.ValidationMessage("City")
            </td>
        </tr>
        <tr>
            <td>Province:</td>
            <td>
                <input type="text" name="Province" value="@Model.Province" />
            </td>
            <td>
                @Html.ValidationMessage("Province")
            </td>
        </tr>
        <tr>
            <td>Postal Code:</td>
            <td>
                <input type="text" name="PostalCode" value="@Model.PostalCode" />
            </td>
            <td>
                @Html.ValidationMessage("PostalCode")
            </td>
        </tr>
        <tr>
            <td colspan="2" align="right">
                <input type="submit" value="Update" asp-page-handler="Update" />
            </td>
        </tr>
    </table>
</form>
@Model.Message

Pages/UpdateItem.cshtml
@page
@model BAIS3150Project.Pages.UpdateItemModel
@{
    Layout = "_Layout";
    ViewData["Tittle"] = "Update Item";
}
<h1>Update Item</h1>
<form name="form" method="post">
    <table>
        <tr>
            <td>Item Code:</td>
            <td>
                <input type="text" name="SearchItemCode" />
            </td>
            <td>
                @Html.ValidationMessage("SearchItemCode")
            </td>
        </tr>
        <tr>
            <td colspan="2" align="right">
                <input type="submit" value="Search" asp-page-handler="Search" />
            </td>
        </tr>
        <tr>
            <td>Item Code:</td>
            <td>
                <input type="text" hidden name="ItemCode" value="@Model.ItemCode" />
                <input type="text" disabled value="@Model.ItemCode" />
            </td>
            <td>
                @Html.ValidationMessage("ItemCode")
            </td>
        </tr>
        <tr>
            <td>Description:</td>
            <td>
                <input type="text" name="Description" value="@Model.Description" />
            </td>
            <td>
                @Html.ValidationMessage("Description")
            </td>
        </tr>
        <tr>
            <td>Unit Price:</td>
            <td>
                <input type="text" name="UnitPrice" value="@Model.UnitPrice" />
            </td>
            <td>
                @Html.ValidationMessage("UnitPrice")
            </td>
        </tr>
        <tr>
            <td>Quantity:</td>
            <td>
                <input type="text" name="Quantity" value="@Model.Quantity" />
            </td>
            <td>
                @Html.ValidationMessage("Quantity")
            </td>
        </tr>
        <tr>
            <td colspan="2" align="right">
                <input type="submit" value="Update" asp-page-handler="Update" />
            </td>
        </tr>
    </table>
</form>
@Model.Message